f = open('book.txt','w',encoding='utf-8')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.write('水浒传\n')
f.seek(0)
